# Generated by Django 5.1.2 on 2024-10-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='total_seats',
            field=models.IntegerField(default=0),
        ),
    ]
